import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Bread } from '../components/BreadCrumb'
import { Content } from '../components/Content'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-big.ico" />
      </Head>
      
      <Header/>

      <Bread/>
      <Content/>
      <Footer/>


      
      
    </>
  )
}
